notifications:
  email: false

git:
  depth: 3

services:
  - postgresql

language: php
sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - DB=sqlite
  - DB=postgres

matrix:
  fast_finish: true

before_install:
  - composer install
  - npm install -g jshint

script:
  - jshint assets/js/{core,components}
  - ./vendor/bin/phpunit -c tests/units.$DB.xml
  - ./vendor/bin/phpunit tests/configtest
